### ISSUE TITLE
Managing Topic Assignment in the Activity- "Beginner's Guide to Mobile Web Development"

### ISSUE THREAD

**Issue by ayushdev** [danivijay/gucs-wiki#20]
We can use Github in order to assign topics and check whether the tutorials are submitted or not. This will allow to check whether the tasks have completed within the deadline or not. The assignees can also check whether the they submissions have been published or they are pending due to some errors in the Medium Story/ Youtube Video.

Below is the list of the topics and the Slack Username of the people, who were assigned the topic.

**Task List Set 1**

1) Git Installation along with its commands.(Taken- Balson)

2) Basic Github Tutorial.(Taken - Devesh)

3) package.json file and its contents. (Taken- Shaan)

4) Service Workers and it’s benefits.(Taken- anmol)

5) IndexedDB commands explanations & concept.(Taken- Dani M Vijay)

6) Promises and its benefits along with examples. (Taken- Shaan)

7) What’s new in HTML5. (Taken- Devesh)

8) What is NPM and why use it. Commonly used NPM commands. (Taken- dharmateja)

9) Explanation of Cache API. (Taken- ritikrishu)

10) What’s new in CSS3.(Taken- Devesh)

**Task List Set 2**

1) Javascript Debugging using Modern Tools. (Taken- Devesh)

2) Arrow Function in Javascript. (Taken - Gurpal)

3) Writing Accessible HTML (Taken- Sameer Khan )

4) Javascript Performance (Taken- Shaan)

5) Javascript Animations (Taken- Avijit)

6) Accessible Rich Internet Applications(ARIA) Suite (Taken- manajit.pal)

7) Media Queries (Taken- vignesh)

8) Google’s Material Design (Taken- Karthikeyan)

9) CSS Selectors (Taken- Faizan Khan)

10) Javascript Hoisting (Taken- Scorpionk)

**Task List Set 3**

1) Observables vs Promises - An introduction to RxJS. (Taken- jadon.devesh98)

2) Web Image Formats. (Taken - a0ghosh_udacity)

3) Introduction to ES6. (Taken- s.karthik.coder )

4) Javascript Closure (Taken- aryaksengupta)

5) JavaScript Event Loop. (Taken- shardendukumargautam)

6) Flexbox in CSS (Taken- manajitpal95)

7) CSS Specificity & It’s Importance (Taken- 14mcei14)

8) ES6 Classes. (Taken- smritigaba548)

9) Introduction to Webpack. (Taken- s.pathak5995)

10) Working with CSS variables. (Taken- manajitpal95)

11) An introduction to Node.js (Taken- jatin11gidwani)

12) A guide to Babel (Taken- sathannan)

13) Top Five Favourite/Most Used NPM Packages (Taken- sathannan)

14) Web App vs Native App (Taken- gurkirpal204 )

15) Introduction to Polyfills (Taken- anurag-majumdar )

**Task List Set 4**

1) 4 Reasons to become a Web Developer. (Taken- Mohan Sharma)

2) The Fetch API. (Taken- Swapnil)

3) Arrow Functions in Javascript ES6. (Taken- Twisha)

4) “Super” and “Extends” in Javascript ES6 - Understanding the Tough Parts. (Taken- anurag-majumdar)

5) Javascript Sets and Weaksets. (Taken- Aryak)

6) Javascript Maps and Weakmaps. (Taken- nben)

7) Javascript Proxies. (Taken- Kartik Sharma)

8) Javascript Generators. (Taken- Shaan)

9) Javascript Symbols. (Taken- Abdul Kadir)

10) Transpiling. (Taken- Gaurav Yadav)

11) Heroku App Deployment using CLI. (Taken- sounak07)

12) Comparison of Popular Javascript Front End Frameworks. (Taken- manajit.pal)

13) One off Event Listeners in JS. (Taken- ashwani)

14) VDOM vs lit-html (Taken- Karthikeyan)

15) Auditing Websites using Audits 2.0 and Lighthouse. (Taken- Priyanka M)

16) Shadow DOM. (Taken- /anmol)

17) Resize Observer. (Taken- Ashwin.Wadte)

18) Libraries vs Frameworks. (Taken- Chaitanya)

19) Accessibility Object Model (AOM). (Taken- Biboswan)

20) Background Fetch. (Taken- Dani M Vijay)

21) Auto Deployment using BitBucket and Heroku. (Taken- manajit.pal)

22) JS Design Patterns (Taken- anu-007)

23) PouchDB (Taken- Priyanka M)

24) Converting a Django App to a PWA. (Taken- Scorpionk)

25) Push Notifications. (Taken- Rushali)

26) Converting an ASP.NET Core App to a PWA. (Taken- Ashwini)

27) Introduction to Angular 4. (Taken- nikhil)

28) Introduction to Web Assembly. (Taken- pmishra2702)

29) Hybrid Apps v/s Native Apps. (Taken- AkashHamirwasia )

30) Async Await. (Taken- Jitesh Manglani)

31) Which Javascript Framework you should choose? (Taken- pmishra2702)

32) Introduction to React. (Taken- drenther)

33) Web Components (Taken- prabha)

**Tutorial Submitted Till Date-**

1. [JS Frameworks: A brief overview](https://medium.com/beginners-guide-to-mobile-web-development/js-frameworks-a-brief-overview-4b8754c3f1d5)
2. [PWA with WordPress Without Coding](https://medium.com/beginners-guide-to-mobile-web-development/making-a-pwa-with-wordpress-from-scratch-part-1-sans-code-69c1b9cbf955)
3. [Shadow DOM](https://medium.com/beginners-guide-to-mobile-web-development/shadow-dom-10d75fea1daf)
4. [Accessibility Object Model (AOM)](https://medium.com/beginners-guide-to-mobile-web-development/accessibility-object-model-aom-part-1-8dc257fdb2d2)
5. [“Super” and “Extends” in JavaScript ES6 — Understanding the Tough Parts](https://medium.com/beginners-guide-to-mobile-web-development/super-and-extends-in-javascript-es6-understanding-the-tough-parts-6120372d3420)
6. [ResizeObserver — a new way to attach listeners to listen to size changes of observed elements](https://medium.com/beginners-guide-to-mobile-web-development/resizeobserver-a-new-way-to-attach-listeners-to-listen-to-size-changes-of-observed-elements-915c4c3f19c1)
7. [Convert Django Website to a Progressive Web App](https://medium.com/beginners-guide-to-mobile-web-development/convert-django-website-to-a-progressive-web-app-3536bc4f2862)
8. [Introduction to React](https://medium.com/beginners-guide-to-mobile-web-development/introduction-to-react-24784ab1ef2d)
9. [JavaScript: Introduction to Symbols!](https://medium.com/beginners-guide-to-mobile-web-development/javascript-introduction-to-symbols-3b0db80b4c51)
10. [async-await in Javascript](https://medium.com/beginners-guide-to-mobile-web-development/async-await-in-javascript-160ac5144b57)
11. [Introduction to Web Assembly](https://medium.com/beginners-guide-to-mobile-web-development/introduction-to-web-assembly-6cb6466a3478)
12. [One-off event listeners in JavaScript](https://medium.com/beginners-guide-to-mobile-web-development/one-off-event-listeners-in-javascript-92e19c4c0336)
13. [Web Push Notifications](https://medium.com/beginners-guide-to-mobile-web-development/web-push-notifications-9a785db55569)
14. [Auto-Deployment Using Bitbucket and Heroku](https://medium.com/beginners-guide-to-mobile-web-development/auto-deployment-using-bitbucket-and-heroku-521b4271cc27)
15. [Navigating with ES6 Maps and WeakMaps](https://medium.com/beginners-guide-to-mobile-web-development/navigating-with-es6-maps-and-weakmaps-e285ddb90c89)
16. [JavaScript Proxies](https://medium.com/beginners-guide-to-mobile-web-development/javascript-proxies-14a6784e4f63)
17. [Everything you need to know about ES6 Arrow Functions and lexical ‘this’](https://medium.com/beginners-guide-to-mobile-web-development/everything-you-need-to-know-about-es6-arrow-functions-and-lexical-this-19cce1a49bdf)
18. [Does using let and const really prevent hoisting?](https://medium.com/beginners-guide-to-mobile-web-development/does-using-let-and-const-really-prevent-hoisting-1ff0696dd803)
19. [Closures — A moment of truth (Functional Programming and JavaScript)](https://medium.com/beginners-guide-to-mobile-web-development/closures-in-functional-programming-and-javascript-3ed730e08fc2)
20. [Evolution from Web Sites to Web Apps — PWA](https://medium.com/beginners-guide-to-mobile-web-development/evolution-from-web-sites-to-web-apps-pwa-6aa25aeecd2b)
21. [Introduction to ES6](https://medium.com/beginners-guide-to-mobile-web-development/introduction-to-es6-c4422d3c5664)
22. [Introduction to Node.js](https://medium.com/beginners-guide-to-mobile-web-development/introduction-to-node-js-8ea696da2b00)
23. [Flexbox in CSS](https://medium.com/beginners-guide-to-mobile-web-development/flexbox-in-css-dcc724c5cfb2)
24. [Working With CSS Variables](https://medium.com/beginners-guide-to-mobile-web-development/working-with-css-variables-3f8314cdeb56)
25. [Introduction to Polyfills & their Usage](https://medium.com/beginners-guide-to-mobile-web-development/introduction-to-polyfills-their-usage-9cd6db4b1923)
26. [CSS Specificity and it’s importance](https://medium.com/beginners-guide-to-mobile-web-development/css-specificity-its-importance-9633e568ee7f)
27. [Introduction to Webpack 4](https://medium.com/beginners-guide-to-mobile-web-development/introduction-to-webpack-4-e528a6b3fc16)
28. [Web App vs Native App](https://medium.com/beginners-guide-to-mobile-web-development/web-app-vs-native-app-b3da1baafcc9)
29. [A Guide To Google Material design](https://medium.com/beginners-guide-to-mobile-web-development/a-guide-to-google-material-design-977315149ea5)
30. [JavaScript Animations!Why Not.?](https://medium.com/beginners-guide-to-mobile-web-development/javascript-animations-why-not-df0d03c8738c)
31. [ARIA Rich Internet Application Suite](https://medium.com/beginners-guide-to-mobile-web-development/aria-rich-internet-application-suite-4e28c9d660bc)
32. [Are you Writing Accessible HTML?](https://medium.com/beginners-guide-to-mobile-web-development/writing-accessible-html-5c8e99bf9944)
33. [What are CSS Selectors?](https://medium.com/beginners-guide-to-mobile-web-development/what-are-css-selectors-1ce3796c326c)
34. [Introduction to npm and basic npm commands](https://medium.com/beginners-guide-to-mobile-web-development/introduction-to-npm-and-basic-npm-commands-18aa16f69f6b)
35. [JavaScript Hoisting](https://medium.com/beginners-guide-to-mobile-web-development/javascript-hoisting-f58f9252de3c)
36. [Service Worker](https://medium.com/beginners-guide-to-mobile-web-development/service-worker-79f655b85465)
37. [Why package.json? | npm basics](https://medium.com/beginners-guide-to-mobile-web-development/why-package-json-npm-basics-cab3e8cd150)
38. [Cache Recipes](https://medium.com/beginners-guide-to-mobile-web-development/cache-recipes-40461395b4c1)
39. [JavaScript Essentials: Understanding Promises](https://medium.com/beginners-guide-to-mobile-web-development/javascript-essentials-understanding-promises-200657e11667)
40. [Cache me if you can !!](https://medium.com/beginners-guide-to-mobile-web-development/cache-me-if-you-can-7f68788b9da2)
41. [Arrow function in JS](https://medium.com/beginners-guide-to-mobile-web-development/arrow-functions-in-js-c9281627ce15)
42. [What Exactly is GitHub Anyway?](https://medium.com/beginners-guide-to-mobile-web-development/what-exactly-is-github-anyway-e7d0ef459002)
43. [Git Installation Along With It’s Commands.](https://medium.com/beginners-guide-to-mobile-web-development/git-installation-along-with-its-commands-9e6a67238803)
44. [Taming IndexedDB](https://medium.com/beginners-guide-to-mobile-web-development/taming-indexeddb-1-tbd-96a222512ea1)
45. [Heroku Deployment of Node.js App](https://www.youtube.com/watch?v=1oW1wvDecR4&feature=youtu.be)

**Comment by ashwani99** [comment]
@ayushdev Can you give me an indication of which ones among these are not yet submitted?

**Comment by danivijay** [comment]
Tasklist is already here : https://github.com/danivijay/gucs-wiki/blob/master/activities/Beginners%20guide%20to%20mobile%20web%20development.md

**Comment by anurag-majumdar** [comment]
Hi guys, wanted to say that I had published an article for Task List 3 which is not included here, it was regarding Introduction to Polyfills. The discussion post was present on Slack for it.

Also, I can see not all articles have been selected for task lists before 4.

**Comment by ashwani99** [comment]
@ritikrishu I am working on it. I am not sure about having Github profiles here as we don't have the GitHub handle of all the members. 

@anurag-majumdar If the tasks were approved, I will check and update the list

**Comment by ayushdev** [comment]
@ashwani99 Ya, I have added it.

**Comment by anurag-majumdar** [comment]
@ayushdev Thanks a lot.

**Comment by ashwani99** [comment]
@ayushdev The names of articles are different with the task assigned. This makes the job harder to match the articles.

**Comment by sounak07** [comment]
It would be good if we add the links to the completed tasks.It would make the navigation easier.

**Comment by ashwani99** [comment]
@ayushdev Please remove the @ symbols. This is causing people get unnecessary emails to their inbox. Some people are receiving the emails because they have same GitHub handle as the slack handles

**Comment by ayushdev** [comment]
@ashwani99 @sounak07 Done.
